name: ci-build
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*'
  pull_request:
    branches:
      - master
env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: 'manikmagar/muleflowdiagrams'
jobs:
  build:
    runs-on: ubuntu-latest
    name: build-test-docker
    steps:
      - uses: actions/checkout@v1
      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
      - name: Test Docker image
        run: |
          docker version --format '{{.Server.Version}}'
          docker run --rm $IMAGE_NAME --version

