name: publish-docker
on:
  push:
    tags:
      - '[012].[0-9]+.[0-9]+*'
jobs:
  build:
    runs-on: ubuntu-latest
    name: publish-docker
    steps:
      - uses: actions/checkout@v1
      - name: Build and Push Docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: manikmagar/muleflowdiagrams
          tag_with_ref: true